language: node_js
node_js:
- '0.11'
before_script:
- git config --global user.email "pizzadealer@proux.de"
- git config --global user.name "Pizza Dealer"
- git config --global push.default simple
- git config credential.helper "store --file=.git/credentials"
- git config merge.defaultToUpstream true
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git remote set-url origin https://github.com/nicolindemann/pizza.de-dealer.git
- git checkout -b data
- git fetch
- git pull origin -q
script:
- date +%s > updated
- date +%s
- git add .
- git commit -m "New Data"
- git fetch
- git push origin data -f
env:
  global:
  - secure: cXVToh8m28X15J7KL4suLcZNTdfZChEKbiNLPIT+tj/8rih3Irojc023WSt1/+j8aSEOLd6tZO46alyeRhOQkTXX4O+Src++DRB3FfPBqkqLjiXRCr16UWZnQ5XzZ4Er7Rsn5XRseQJDgh8wGlOnOr+MZxqDDwckW0e+59sctjo=
branches:
  only:
  - master
  except:
  - data
